title: Plausible Analytics
tagline: Simple, privacy-friendly alternative to Google Analytics
permalink: /blog/:title
highlighter: rouge
url: https://greymar.io
description: 'Plausible is a lightweight and open-source web analytics tool. Your website data is 100% yours and the privacy of your visitors is respected.'
show_excerpts: true
css_dir: 'assets/css'
twitter:
  username: ukutaht
feed:
  path: /blog/feed.xml

jekyll-minifier:
  uglifier_args:
    harmony: true

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/plausible_promo.jpg

collections:
  articles:
    output: true
  changes:

include:
  - _redirects
  - _headers

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-postcss
 - jekyll-purgecss
 - jekyll-minifier

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - tailwind.config.js
  - .gitignore
  - vendor
